name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  verify_exercises:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25

      - name: Run flake checks
        run: nix flake check -Lvv --log-format bar-with-logs
