name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  verify_exercises:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa

      - name: Run flake checks
        run: nix flake check -Lvv --log-format bar-with-logs
